spring.application.name=oficinaconectada
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
application.security.jwt.secret-key=${JWT_SECRET}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
application.security.jwt.expiration=86400000
spring.flyway.enabled=true
spring.flyway.locations=${MIGRATIONS_DB}
spring.flyway.sql-migration-prefix=
spring.flyway.sql-migration-separator=_
spring.h2.console.enabled=false