
spring.application.name=oficinaconectada
spring.datasource.url=jdbc:mysql://localhost:3306/oficinaconectada
spring.datasource.username=***REMOVED***
spring.datasource.password=***REMOVED***
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
application.security.jwt.secret-key=***REMOVED***
application.security.jwt.expiration=86400000
spring.h2.console.enabled=false